### ISSUE TITLE
What is the css class of the white border to the right of the left sidebar?

### ISSUE THREAD

**Issue by SilverMarcs** [beeper/themes#10]
This is what i mean. Marked with pink arrow

<img width="318" alt="Screenshot 2023-06-20 at 1 50 46 AM" src="https://github.com/beeper/themes/assets/77480421/3c6df0ed-239e-4ce8-8a98-02c8b76c5dcd">

**Comment by SilverMarcs** [comment]
https://github.com/beeper/themes/pull/7/commits/0882080617f256b4ea9dd92500fdab06401d9585

ok doing this and adding properties for border-left helps. is there a better way?

**Comment by 0xdevalias** [comment]
> [0882080](https://github.com/beeper/themes/commit/0882080617f256b4ea9dd92500fdab06401d9585)
> 
> Doing this and adding a border-right to left side panel does the trick but is there a better way?

@SilverMarcs I just had a quick look, and I think targeting `.mx_ResizeHandle` is definitely the right approach. Both `-webkit-box-shadow` and `box-shadow` are essentially doing the same thing, just prefixed for older browser compatibility. In devtools, if I disable both of those styles, then the white border goes away:

![image](https://github.com/beeper/themes/assets/753891/ecfbc36f-dec5-4e7b-b526-f21f2939d7ee)

**Before:**
![image](https://github.com/beeper/themes/assets/753891/259446e2-3deb-4cdf-89f1-c3ba6de9f6a9)

**After:**
![image](https://github.com/beeper/themes/assets/753891/8fbd5836-53fc-4e3a-8eb2-3e1259f7af1e)

---

We can make this really obvious by changing the colour of the `box-shadow` there (eg. to red), and observing the results:

```css
.mx_MatrixChat > .mx_ResizeHandle, .mx_RightPanel_ResizeWrapper .mx_ResizeHandle {
  box-shadow: #f00 1px 0px 0px 0px inset;
}
```

![image](https://github.com/beeper/themes/assets/753891/8c230840-8e12-4621-9995-531612e84240)

---

So I think you could just use the following rule (very similar to the one you had, but doesn't touch `margin`:

```css
.mx_MatrixChat > .mx_ResizeHandle, .mx_RightPanel_ResizeWrapper .mx_ResizeHandle {
  -webkit-box-shadow: none;
  box-shadow: none;
}
```
